import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")
HISTORY_FILE = os.path.join(OUTPUT_DIR, "history.json")
SAMPLE_DIR = os.path.join(BASE_DIR, "data", "sample")

ALLOWED_IMAGE_TYPES = [".jpg", ".jpeg", ".png", ".bmp"]
ALLOWED_VIDEO_TYPES = [".mp4", ".avi", ".mov"]
MIN_IMAGE_WIDTH = 120
MIN_IMAGE_HEIGHT = 120

RESIZE_WIDTH = 640
BLUR_KERNEL = 5
CLAHE_CLIP = 2.0
CLAHE_GRID = 8
DARK_MEAN_LIMIT = 90

CANNY_LOW = 60
CANNY_HIGH = 160
MORPH_KERNEL = 3

ROI_BOTTOM_LEFT = (0.03, 1.00)
ROI_TOP_LEFT = (0.40, 0.58)
ROI_TOP_RIGHT = (0.60, 0.58)
ROI_BOTTOM_RIGHT = (0.97, 1.00)

HOUGH_RHO = 1
HOUGH_THETA_STEPS = 180
HOUGH_THRESHOLD = 30
HOUGH_MIN_LINE_LENGTH = 25
HOUGH_MAX_LINE_GAP = 60

MIN_SLOPE = 0.4
MAX_SLOPE = 5.0
GOOD_SEGMENT_COUNT = 6
GOOD_EDGE_STRENGTH = 90.0

WEIGHT_SEGMENTS = 0.20
WEIGHT_COVERAGE = 0.30
WEIGHT_CONTINUITY = 0.25
WEIGHT_STRENGTH = 0.25

CLEAR_LIMIT = 70
FADED_LIMIT = 40

LANE_COLOR = (0, 255, 0)
SEGMENT_COLOR = (0, 140, 255)
LANE_THICKNESS = 8
